apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: mongo-data-volume-1
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  gcePersistentDisk:
    pdName: mongo-ssd-disk-1
